name: Compile docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install pandoc
      run: |
        cd ~
        wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
        sudo apt install -y ./pandoc-2.9.2.1-1-amd64.deb

    - name: Install other dependencies with apt
      run: |
        sudo apt install -y texlive-latex-extra

    - name: Checkout submodules
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive

    - name: Make docs
      run: make

    - uses: actions/upload-artifact@v2
      with:
        name: cal-consulta-proj.pdf
        path: cal-consulta-proj.pdf
